# Generated by Django 3.2.7 on 2021-10-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_auto_20211004_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserForm',
        ),
    ]
