# Generated by Django 3.2.7 on 2021-10-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_rename_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
    ]
