# Generated by Django 3.2.7 on 2021-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0009_auto_20211118_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
