# Generated by Django 3.2.7 on 2021-11-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0011_like_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='news_api.Profile'),
        ),
    ]
