# Generated by Django 3.2.7 on 2021-12-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0017_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
